# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
    exclude: |
      (?x)(auto_rx/autorx/static)
  - id: end-of-file-fixer
    exclude: |
      (?x)(auto_rx/autorx/static)
  - id: check-added-large-files
  - id: check-executables-have-shebangs
